### ISSUE TITLE
build issues on linux

### ISSUE THREAD

**Issue by alanhaw** [tzlaine/text#102]
A note on compiling on linux (Ubuntu 16.04) with g++ 8.1 and boost 1.68.0:
- BOOST_ROOT needs to be defined in the user's environment.
- the libraries "stdc++ m" need to be explicitly included. This was added in 3 locations:
    - text/benchmark-v1.2.0/CMakeLists.txt
		at line 43 immediately after
                    include(CXXFeatureCheck) 
                add
		    list(APPEND BENCHMARK_CXX_LIBRARIES stdc++ m)
    - text/test/CMakeLists.txt
		at line 56 it becomes
			target_link_libraries(${local_name} text gtest gtest_main stdc++ m)
    - text/test/CMakeLists.txt
		at line 384 just after 
			if (clang_on_linux)
    			target_link_libraries(compile_tests c++)
			endif ()
		the new line is added:
		    target_link_libraries(compile_tests stdc++ m)

Those 3 changes would have to be made conditional on being in the linux environment.
Those changes allow the project compile to go to 13%, at which point it is compiling the bidirectional tests and runs into a compile error:
	/home/alan/projects/text/text/test/bidi_test_507.cpp:24:50:   required from here
/home/alan/projects/text/text/include/boost/text/algorithm.hpp:238:28: error: call of overloaded ‘find_if ... is ambiguous
	first = find_if(first, last, p);
	    ..............^_______________
/home/alan/projects/text/text/include/boost/text/algorithm.hpp:74:14: note: candidate: ‘BidiIter boost::text::find_if(BidiIter, Sentinel, Pred)	...
/usr/local/include/boost/container/detail/algorithm.hpp:111:9: note: candidate: ‘InputIt boost::container::find_if(InputIt, InputIt, UnaryPredicate)	...
/usr/include/c++/8/bits/stl_algo.h:3921:5: note: candidate: ‘_IIter std::find_if(_IIter, _IIter, _Predicate) ...

**Comment by tzlaine** [comment]
This build fine for me on a native Linux system, a Linux VM, and all the Travis machines:

https://travis-ci.org/tzlaine/text/builds/436893872

**Comment by alanhaw** [comment]
After additional investigation, the compile error was cured by altering line 238 of the file text/include/boost/text/algorithm.hpp from:
    first = find_if(first, last, p);
to 
    first = text::find_if(first, last, p);

Then 3 more additions of "stdc++ m":
  In line 46 of text/test/CMakeLists.txt so the line becomes -
    target_link_libraries(generate_tailoring_rule_tests text gtest gtest_main stdc++ m)
and on line 6 of text/example/CMakeLists.txt so it becomes -
    target_link_libraries(${name} text stdc++ m)
and on line 57 of text/example/CMakeLists.txt so it becomes - 
    target_link_libraries(rope_editor text ${Boost_LIBRARIES} ${CURSES_LIBRARIES} stdc++ m)

With those changes the default project (plus the BUILD_EDITOR addition) will build.

I expect there are more instances of where "stdc++ m" are required in other optional parts of the project. (Probably anywhere the expression "clang_on_linux" is used in the CMakeLists.txt files.)
