### ISSUE TITLE
SBO guarantee for grapheme

### ISSUE THREAD

**Issue by johelegp** [tzlaine/text#106]
It'd be nice if the library could guarantee the size of the SBO in `grapheme`. Then one could handle `grapheme`s by value more often with the structural knowledge of the program.

**Comment by tzlaine** [comment]
There is another side to this reasoning.  Currently, SBO size is an implementation detail I am free to change whenever.  If I document the SBO size, and you rely upon it for optimizations, I will break those optimizations when/if I change the SBO size.  Moreover, this library is targeting standardization, and the argument I just made applies there.  I'm unwilling to break with this convention from the standard.
