### ISSUE TITLE
MWE front and center

### ISSUE THREAD

**Issue by NAThompson** [tzlaine/text#128]
I saw your post on the Boost mailing lists; I'm super excited for your library!

As a small point of feedback, I know nothing about unicode, and don't want to. Going through the docs of your library, it seemed like it was aimed at people who are very technically adept, understand Unicode and share your frustration with the lack of tooling.

But I was just looking for how to spit out the symbol for a Laplacian in an error message!

Could you put a simple minimal working example showing how to spit out some mathematical symbols, maybe some subscripts/superscripts, with Greek letters, front and center? In the README would be fine.

(Mathematical symbols aren't required, of course. I guess an emoji would be just fine as well.)

**Comment by tzlaine** [comment]
You are definitely the target audience for this library, but I don't really understand what you're asking.  Are you asking how you represent these symbols, how you print them, both, or something else?  If you can post pseudocode of what you want to do, indicating the parts you don't know how to do, that might help.

**Comment by NAThompson** [comment]
How about this as a representative of what I want to do?

```cpp
if (matrix_has_negative_eigenvalue) {
boost::uft8 err_msg = "-∇² is positive definite, but found discretization with λ<0";
throw std::domain_error(err_msg);
}
```

**Comment by tzlaine** [comment]
This will already work on any system that supports UTF-8 in the terminal.  That's all major platforms now, even Windows (though you have to adjust some settings to get it to work on Windows).  You can just use a std::string for this, since it's UTF-8.  In fact, you have to, if you want to interoperate with std::domain_error().
