### ISSUE TITLE
Comparison of text_sort_key inconsistent

### ISSUE THREAD

**Issue by Flamefire** [tzlaine/text#131]
Just scanning through the code I'm highly doubtful about this: https://github.com/tzlaine/text/blob/091143ea3502a0955148bb95ac22e364753aebec/include/boost/text/collate.hpp#L93-L123

E.g. Why is `operator>=` using `compare` which none of the others do and why is `operator<=` using `boost::text::v1::compare`? It seems those 2 are the same, but one is fully qualified?

Also `compare`s docu says `Returns 0 if the given sort keys are equal, a value < 0 if `lhs` is
        less than `rhs`, and a value > 0 otherwise.` so why is only `<0` (or `>0`) checked in `<=` and `>=`?

**Comment by tzlaine** [comment]
Sloppiness!  Looks like I have copy/paste error in the difference between op<= and op>=.  They respectively should just use !(rhs <lhs) and !(lhs <rhs).
