### ISSUE TITLE
range-v3 compatibility

### ISSUE THREAD

**Issue by mikezackles** [tzlaine/text#133]
Forgive my ignorance, but are the ranges in this library intended to interoperate with something like range-v3?

I'm trying to do something like this:
```
auto lines = boost::text::lines(graphemes);
for (auto line : lines | ranges::views::drop(5)) {
  ...
}
```

Using the latest boost text master (https://github.com/tzlaine/text/commit/b04cd3e129a7f5e242af4a07561c4246097f4ab8), range-v3 version 0.10.0, and clang 9.0.1, I get a compiler error: `candidate template ignored: could not match 'view_closure' against 'lazy_segment_range'`.

Is there a recommended idiom? Or is this sort of thing not supported? Should I be using a different ranges implementation? Or is this a bug?

Thank you! This is a neat library!

**Comment by mikezackles** [comment]
I dug into this a bit today.

This fails due to a missing postfix increment iterator for `const_lazy_segment_iterator`:
```
using I = decltype(lines.begin());
static_assert(ranges::weakly_incrementable<I>);
```
According to the docs for `stl_interfaces`, it seems like the fix is just to add something like a `using base_type::operator++;`.

This also fails:
```
using foo = ranges::range_tag_of<decltype(lines)>;
```
The above appears to check the stronger concepts first, falling back to weaker concepts via SFINAE. So in this case, random access is checked first, but it causes a hard error due to the noexcept specifications in `iterator_interface`.

See the above commit for the changes that allowed me to compile this particular example, but I realize there's probably more work to do. Hopefully this is helpful, and please let me know if I'm misunderstanding things. I'll try to take it a bit further tomorrow. Thanks!

**Comment by tzlaine** [comment]
Hm.  I fixed the missing operators, but the ither part (the part where you had to change the point at which the noexcept expression was evaluated) should not be necessary.  According to http://eel.is/c++draft/except.spec#13 and this StackOverflow article: https://stackoverflow.com/questions/51501156/evaluating-noexcept-specifier-before-template-type-deduction , the way they're written now should "just work".

So, to be clear: you're using Clang 9, range-v3 master/HEAD, and is there any other info you can provide about the particulars of your circumstance?

**Comment by mikezackles** [comment]
[Here is a repository](https://github.com/mikezackles/textrange-repro) that (on my system) reproduces the failure against the current master/HEAD for both text and range-v3.

I'm running Arch Linux with clang 9.0.1.

To be clear, I didn't mean to imply that my original changes are correct, just that they fix the issue on my system. (I'm not a SFINAE wizard.)

My changes were (very hastily) based on [this older question on stackoverflow](https://stackoverflow.com/questions/33665208/sfinae-and-noexcept-specifier) which cites the standard [here](http://eel.is/c++draft/temp.deduct#7).

I also just noticed that gcc 9.3.0 runs into the same errors, but my friend function hack doesn't appear to work there.

Again, I'm not sure what's correct -- just trying to provide as much information as possible.

**Comment by mikezackles** [comment]
I took a closer look at your links. Check Barry's note at the end of his answer in the StackOverflow article you linked:

> Note also that substitution failure in the exception specification is not part of the immediate context, and would not be a SFINAE-friendly error.

**Comment by tzlaine** [comment]
To be clear, I think you're doing exactly the right thing here.  If I sounded dismissive before, that was not my intention.  I'm just trying to figure out the shape of the problem at this point.  If I need to work around compiler bugs, I probably will, but if I've made a mistake that might mean a different change is needed, etc.  I'm in touch with Barry now privately (he's a friend, and know a lot more about this part of the language than I do), and we'll get to the bottom of it I'm sure.

**Comment by mikezackles** [comment]
> I'm in touch with Barry now privately (he's a friend, and know a lot more about this part of the language than I do), and we'll get to the bottom of it I'm sure.

Awesome! I didn't think you were being dismissive, and I'm looking forward to seeing this resolved properly.

I was struggling with the hidden friends and just made a commit that attempts to fix some of them if it's helpful. Thanks for digging into this.

**Comment by tzlaine** [comment]
The key here is that the expression in the noexcept specifier are fine as long as they are guarded by an at-least-as-strict SFINAE guard.  So, `foo() noexcept(noexcept(expr))` might give a hard error, whereas `foo() noexcept(noexcept(expr)) -> decltyp(expr)` will not.  There was only one place where this matters to range-v3, and I've made that change there in the stl_interfaces repo:

https://github.com/tzlaine/stl_interfaces/commit/ad2ea1a657f62417adf2fc1878d860ec62e40cda

The change associated with the fix for this issue is much larger because it's a bulk copy from the stl_interfaces sources.

**Comment by tzlaine** [comment]
BTW, thatnks a ton for making a self-contained repro case as a standalone repo!  That was super helpful.

**Comment by mikezackles** [comment]
Happy to help, and thanks for sharing your findings! I was definitely missing some `remove_reference`s, and the explicit lvalue ref `declval`s make sense to me I think.

I verified that the latest (50ca2c6) does fix the issue for clang, but building with gcc still fails for me (v9.3.0). That's what some of my other modifications were aimed at, but they were all similar issues. (I didn't take the time to explore why gcc takes a different path than clang.) More specifically, these additional operators trigger hard errors with gcc (using the same repro project):

* `operator+(difference_type, Derived)`
* `operator-=(difference_type)`
* `operator-(Derived, difference_type)`

If you look at my commit above, I took the approach you used with the hidden friend functions, but I had to template on the difference type to create a dependency to SFINAE on (or whatever the proper terminology is). That seemed reasonably OK at a glance as ADL should still work, but I guess there might be other gotchas. Perhaps there's a better way.

Just a thought, but it might make sense to give all the operators in `iterator_interface` the same treatment to be safe.

Thanks again!

**Comment by tzlaine** [comment]
Yep.  I missed these because I was only looking at `range_tag_of`.

**Comment by tzlaine** [comment]
Looks like this is going to work for Clang 9 and GCC 9, but it will take some rework for older compilers it seems -- it broke everything before GCC 9 and Clang 9 in CI.

**Comment by mikezackles** [comment]
Ugh, sorry for opening a can of worms. Can confirm everything checks out on my end.

**Comment by tzlaine** [comment]
No worries.  It needed to be fixed.  I'm jut glad that Clang 9 and GCC 9 actually finally do the right thing for deduced return type, even if the earlier compilers don't.  I've been working around that deficiency for too long.
