### ISSUE TITLE
lazy_segment_range iterators are missing postfix increment

### ISSUE THREAD

**Issue by mikezackles** [tzlaine/text#134]
It seems like these are intended to be forward iterators. According to the [stl_interfaces docs](https://tzlaine.github.io/stl_interfaces/doc/html/boost_stlinterfaces/tutorial___iterator_interface_.html), the base class postfix increment needs to be exposed:

```
using base_type = boost::stl_interfaces::
    iterator_interface<node_iterator<T>, std::forward_iterator_tag, T>;
using base_type::operator++;
```
Is there a reason this was left out, or was it just an oversight?

Note that this is a blocker for #133.

**Comment by tzlaine** [comment]
Definitely an oversight.  This is now fixed.
