### ISSUE TITLE
C++20: u8string and char8_t literals

### ISSUE THREAD

**Issue by igoloe** [tzlaine/text#135]
Hi, great work.
Are there any plans to adapt the proposed reference implementation to use std::u8string, boost::text::u8string and char8_t literals instead of std::string, boost::text::string and char literals, if u8 defaults to char8_t literals?

**Comment by tzlaine** [comment]
Yes, although there needs to be widespread support for those before I add them.  There should probably be conversions from `char8_t *` and `std::u8string` to `boost::text::text` for instance.

**Comment by tzlaine** [comment]
Fixed by 79b1a5536e86a8cb3b .

**Comment by igoloe** [comment]
Great to see you are investing further in this long required library. I followed the discussions about review of text lib on boost mailing list and hoped to see getting it accepted. Thanks for your effort.
