### ISSUE TITLE
Doc overhaul: remove references to string layer

### ISSUE THREAD

**Issue by tzlaine** [tzlaine/text#166]

**Comment by amitdo** [comment]
Hi Zach,

What about the README.md ?

>This library includes three layers:
>
 >*  The string layer, a set of types that constitute "a better std::string"
 >*  The Unicode layer, consisting of the Unicode algorithms and data
>*  The text layer, a set of types like the string layer types, but providing transparent Unicode support

**Comment by tzlaine** [comment]
Gah!  I always forget the README!  Thanks for pointing this out.
