### ISSUE TITLE
Boost? 

### ISSUE THREAD

**Issue by igoloe** [tzlaine/text#187]
Hi Zach,
do you plan to retry finishing the review process for your library with a recommendation to include it as official part of boost?

You already invested a lot and applied changes for a lot of issues that popped up during review. 

Thx for your effort. Ingo.

**Comment by tzlaine** [comment]
I'm no longer pursuing this as a Boost submission.  The maintainance burden of updating to the new Unicode semantics every year are simply too much for me.  I may submit just the transcoding bits at a later date.  Whatever I submit will track the standard library paper P2728R6 "Unicode in the Library, Part 1: UTF Transcoding" (https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2728r6.html).
