### ISSUE TITLE
'make install' installs gtest, gmock, and benchmark, but not text

### ISSUE THREAD

**Issue by tahonermann** [tzlaine/text#2]
As part of playing with text, I performed a build/install with commands like the following and found that this installed the gtest, gmock, and benchmark dependencies, but not the text library headers, docs, or other artifacts.

```
cd build
cmake -DCMAKE_BUILD_TYPE=DEBUG ..
cmake --build . --config DEBUG --target install -- DESTDIR=/my/sandbox
```

**Comment by tzlaine** [comment]
Text is header-only, so there's nothing to install really.  I'll remove the install targets from the dependencies, though.

**Comment by tahonermann** [comment]
Ok.  For what it's worth, I think an install target is appropriate and useful for header-only projects.  It makes it clear what files are considered relevant for consumers (e.g., excluding tests, scripts, etc...).  An install target also helps package managers identify what files to include in a package.  Finally, having the install provide a CMake find-package helper allows consumers to use standard CMake facilities to locate dependencies.

Going on another tangent... have you considered making `text` not header-only?  I noticed that at least some of the (non-template) inline functions are rather large and probably don't get inlined in code gen anyway.

**Comment by tzlaine** [comment]
I've opened up another ticket for adding a compiled mode.  In my experience, a certain number of users will refuse to use your Boost lib unless it is header only, and a *different* certain number of users will refuse to use your Boost lib unless it is compiled.  I will support both.
