### ISSUE TITLE
Identifier rules missing

### ISSUE THREAD

**Issue by rurban** [tzlaine/text#208]
Unicode has special complicated rules for identifiers to be identifiable,
see https://unicode.org/reports/tr31/ and https://unicode.org/reports/tr39/

Wouldn't it be nice to support identifier checks, 
like if a given name (i.e. path, username, variable name, ...) is a proper identifier in a given context, with a given security profile.
See e.g. my libu8ident for such an implementation.

**Comment by tzlaine** [comment]
This is out of scope for Boost.Text, which is a library for text processing.  I expect less than 1% of its users to need to implement UAX31.  Also, you already did it!
