### ISSUE TITLE
[question] Java string transcoding

### ISSUE THREAD

**Issue by jeremy-coulon** [tzlaine/text#211]
Hello,

First of all, I must say that I don't know much about unicode and encodings.

My application is using Java and JNI bindings.
I have heard that the JVM is not using a real UTF-8 encoding under the hood but a so-called "modified UTF-8". I don't really know what that means.

I would like to transcode these java strings into standard UTF-8 strings (std::u8string).
Does your Text library can help me with this task?
If so, can you guide me to the right direction?

Thanks

**Comment by tzlaine** [comment]
I don't have any idea how Java represents strings, or wht its modified UTF-8 is, so I don'treally know for sure.  However, the `as_utfN` adaptors will produce valid UTF-N from the input, regardless of the input.  The output may have a lot of replcement characters, though. :)  If Java's modified UTF-8 is just UTF-8 in the common case, and your particular text does not fall into the corner cases too often, Boost.Text may work for you.

As an aside, `std::u8string` is not a UTF-8 string per se, it's just `std::basic_string<char8_t>`. IOW, it does nothing to maintain encoding.
