### ISSUE TITLE
Is this ready for use as-is?

### ISSUE THREAD

**Issue by terpstra** [tzlaine/text#94]
I understand this project aims for inclusion in boost as a step towards improving string support in the standard library. However, I need something like this today! Do you foresee keeping this library working in stand-alone form in the future? How much do you expect the API to change?

Thanks a lot for fixing this glaring hole in C++!

**Comment by tzlaine** [comment]
It's pretty much ready for non-MSVC uses right now.  MSVC support will be fixed in the next few days.  I'm mostly just writing docs right now.

I expect the API to change during the Boost review, but I hope not much.
